# version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: t3_chat_build
    environment:
      POSTGRES_DB: t3-chat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports: 
      - "5434:5432"  
    volumes:
      - t3-chat_db_data:/var/lib/postgresql/data
    restart: always

volumes:
  t3-chat_db_data:      